dist: trusty
language: ruby
rvm:
  - 2.3
sudo: required
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
jobs:
  include:
    # - stage: lint
    #   script:
    #     - bundle exec rubocop
    - stage: test
      script:
        - bundle exec rspec
