os: osx
language: ruby
rvm:
  - 2.3
addons:
  chrome: stable
jobs:
  include:
    # - stage: lint
    #   script:
    #     - bundle exec rubocop
    - stage: test
      script:
        - bundle exec rspec
